### PR TITLE
Add attribute option for multiSelectOnClick

### PR DESCRIPTION
**Pull request by jmwohl**

### CODE REVIEW

**Comment by jsiragusa** [comment]
👍

**Comment by jmwohl** [comment]
@jsiragusa I changed this to use sortable options, if you want to check it before I merge...

**Comment by jsiragusa** [comment]
Nice!  👍

**Comment by jmwohl** [comment]
@jsiragusa Ok if I submit a PR for this to the root fork? Probably better not to maintain our own fork if the official maintainer will accept this change.

**Comment by jsiragusa** [comment]
@jmwohl yeah.... I definitely think this is worthy of a PR to the root.

**Pull request merged**
